### ISSUE TITLE
getFrequency returns wrong value

### ISSUE THREAD

**Issue by dquadros** [csdexter/RDA5807M#1]
RDA5807M_BandLowerLimits holds word values, not byte values. My suggestion:

In RDA597M.h change
`extern const byte RDA5807M_BandLowerLimits[];`
for
`extern const word RDA5807M_BandLowerLimits[];`

In RDA5807.cpp change
`const byte RDA5807M_BandLowerLimits[5] PROGMEM = { 8700, 7600, 7600, 6500, 5000 };`
for
`const word RDA5807M_BandLowerLimits[5] PROGMEM = { 8700, 7600, 7600, 6500, 5000 };`
and
`return (word)pgm_read_byte(&RDA5807M_BandLowerLimits[band]) + frequency *
        pgm_read_byte(&RDA5807M_ChannelSpacings[space]) / 10;`
for
`return pgm_read_word(&RDA5807M_BandLowerLimits[band]) + frequency *
        pgm_read_byte(&RDA5807M_ChannelSpacings[space]) / 10;`

**Comment by csdexter** [comment]
Thank you for spotting this, serves me well for coding late at night. Fixed in https://github.com/csdexter/RDA5807M/commit/fc96cde86046f02b722ba2f4c0921640e60967a2
