### ISSUE TITLE
Error: Library function "setFrequency" does not tune after reset command.

### ISSUE THREAD

**Issue by eprive** [csdexter/RDA5807M#3]
I discovered that the function : `bool RDA5807M::setFrequency(word frequency)` does not tune to the new frequency when it is executed while the RDA5807M is still in reset state. The reset state is entered using the command bit (by setting and clearing RDA5807M_FLG_RESET ). This has the effect that the Tuning register is frozen with an invalid value (0x4FC0) until it is unlocked using a succesfull seek or tune command. The behaviour is that the Tuning register (0x03) will only change if the new channel value is written with the RDA5807M_FLG_TUNE command in a single write instruction. So the code in the RDA5807M.cpp library file:

`//Attempt to tune to the requested frequency`
`updateRegister(RDA5807M_REG_TUNING, RDA5807M_CHAN_MASK,
               (frequency * 10 / spacing) << RDA5807M_CHAN_SHIFT);`
`updateRegister(RDA5807M_REG_TUNING, RDA5807M_FLG_TUNE, RDA5807M_FLG_TUNE);`

is incorrect, and should be :

`updateRegister(RDA5807M_REG_TUNING, RDA5807M_CHAN_MASK, 
               (frequency * 10 / spacing) << RDA5807M_CHAN_SHIFT) | RDA5807M_FLG_TUNE);`

or alternatively using a single call to setRegister with all fields set.

**Comment by csdexter** [comment]
Thanks for debugging and reporting this. Do you want to prepare a pull request yourself or are you happy with me fixing it on my side and crediting you in the commit message?

**Comment by csdexter** [comment]
Fixed in 9a29c8e01deb296aeed930eedf1de64f76d8e0eb, closing
